spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nonewbie/springcloudinaction
          search-paths: configrepo
          username: 314320879@qq.com
          password:
  application:
    name: config-server

---
spring:
  profiles: peer1
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: peer2
server:
  port: 18769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
