zuul:
  sensitive-headers:
  routes:
    uaa-service:
      serviceId: uaa-service
      path: /uaaapi/**
    user-service:
      serviceId: user-service
      path: /userapi/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80
spring:
  application:
    name: zuul-gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411