zuul:
  routes:
    zipkin-client:
      serviceId: zipkin-client
      path: /zipkinclientapi/**
      sensitiveHeaders:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80
spring:
  application:
    name: zuul-gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411